### ISSUE TITLE
No translation option on Weblate

### ISSUE THREAD

**Issue by Nekzuris** [plepe/OpenStreetBrowser#201]
I don't see anyway to translate the coordinates spacer options
![image](https://github.com/user-attachments/assets/5b4aa89e-f463-47e0-950c-b806fa34f0da)

**Comment by plepe** [comment]
You are right! I added these right away: ef10e9dd1387fd239a38b0c46fcbf968c821bcd6

**Comment by Nekzuris** [comment]
Thanks, I translated them but they are not visible yet.
Also I found that these are missing:
![image](https://github.com/user-attachments/assets/18a13fa1-c706-46a1-8640-7a6fa4bb411e)
![image](https://github.com/user-attachments/assets/2e5637a7-346e-4e4e-a09f-fde8bd97b764)

**Comment by plepe** [comment]
Thanks for notifying. I fixed this in 083dd827ef9924616e3d30f12174c5e52a78438e.

**Comment by Nekzuris** [comment]
Is it normal that new translations on Weblate are still not showing on openstreetbrowser.org ?

**Comment by plepe** [comment]
The language strings were updated, but I forgot to re-build the code. So, the strings were not being used.

I updated the 'update'-script, so that the code always gets rebuilt.
